

###############Audio Params#################
# Sounds transformations params
sr: 22050
n_fft: 2048
n_stft: 1025
frame_shift: 0.0125
hop_length: 256
frame_length: 0.05
win_length: 1024
mel_freq: 128
max_mel_time: 1024
max_db: 100
scale_db: 10
ref: 4.0
power: 2.0
norm_db: 10
ampl_multiplier: 10.0
ampl_amin: 1e-10
db_multiplier: 1.0
ampl_ref: 1.0
ampl_power: 1.0
################################


###############Hyperparameters#################
# Optimization Hyperparameters #
lr_start: 0.001
device: "cpu"
lr_final: 0.0001
weight_decay: 0.000006
batch_size: 32 #minimum 2
num_workers: 0
text_num_embeddings : 86
embedding_size : 256
encoder_embedding_size : 512
dim_feedforward : 1024
postnet_embedding_size : 1024
encoder_kernel_size : 3
postnet_kernel_size : 5
grad_clip : 1.0
r_gate : 1.0

########### model ######################
model: !new:model.TransformerTTS
  device : !ref <device>
  text_num_embeddings: !ref <text_num_embeddings>
  embedding_size: !ref <embedding_size>
  encoder_embedding_size: !ref <encoder_embedding_size>
  dim_feedforward: !ref <dim_feedforward>
  postnet_embedding_size: !ref <postnet_embedding_size>
  encoder_kernel_size: !ref <encoder_kernel_size>
  postnet_kernel_size: !ref <postnet_kernel_size>
  max_mel_time: !ref <max_mel_time>
  mel_freq: !ref <mel_freq>

modules:
  model: !ref <model>

criterion: !new:model.TTSLoss

# Pretrainer
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        model: !ref <model>

# Text to sequence module
audiofeatures: !new:model.AudioFeatureExtractor

